version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  api:
#    build: .
#    restart: always
#    ports:
#      - "3000:3000"
#    depends_on:
#      - db
#    env_file:
#      - .env

volumes:
  postgres-data: